//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPA_ES.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int Id { get; set; }
        public int CustomerID { get; set; }
        public string AccountID { get; set; }
        public string AccountTo { get; set; }
        public int TransactionTypeID { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public Nullable<int> Mutasi { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual TransactionType TransactionType { get; set; }
    }
}
